// Package db holds the embedded item database generated by tools/build_db.py.
package db

import (
	_ "embed"
	"encoding/json"
	"strings"
)

//go:embed itemdb.json
var raw []byte

//go:embed sounds.json
var rawSounds []byte

// Sounds is every sound the game plays by name, generated by tools/soundindex.
type Sounds struct {
	MuteXor uint32            `json:"muteXor"` // a muted event's ID is its own ID xor this
	Files   map[string]string `json:"files"`   // file package -> SHA1 of the game's own copy
	Sounds  []Sound           `json:"sounds"`
}

// Sound is a Wwise event, by its lower-case name, and every copy of it in the banks.
type Sound struct {
	Name    string    `json:"name"`
	At      []SoundAt `json:"at"`
	Preview *Preview  `json:"p,omitempty"` // nil when the sound's audio was not found
}

// Preview is where the audio of a sound's first sound object sits: a Wwise .wem inside a file package.
type Preview struct {
	File   string `json:"f"`
	Offset int64  `json:"o"`
	Size   int    `json:"n"`
}

// SoundAt is where an event's ID sits: a bank in a file package, and the offset inside the bank.
type SoundAt struct {
	File   string `json:"f"`
	Bank   uint32 `json:"b"`
	Offset int    `json:"o"`
}

// LoadSounds reads the embedded sound list.
func LoadSounds() (*Sounds, error) {
	var s Sounds
	if err := json.Unmarshal(rawSounds, &s); err != nil {
		return nil, err
	}
	return &s, nil
}

type Type struct {
	File       string `json:"file"`
	OrigSha1   string `json:"origSha1"`
	Category   string `json:"category"`
	RarityGlow bool   `json:"rarityGlow"`
	Glow       []int  `json:"glow"`
	Model      []int  `json:"model"`
	Name       []int  `json:"name"`
	Audio      int    `json:"audio"`    // offset of the AudioType value, 0 when the type inherits it
	AudioEnd   int    `json:"audioEnd"` // offset of the None tag ending the default object's properties
}

// Proto is one game-data prototype of an item and where its UnrealClass value is declared.
type Proto struct {
	Path      string `json:"path"`
	Blueprint uint64 `json:"blueprint"`
	Copy      uint8  `json:"copy"`
	Field     uint64 `json:"field"`
	// Inheritors are other items' prototypes that take their UnrealClass from this one.
	Inheritors []Pin `json:"inheritors,omitempty"`
	// Bounds indexes DB.Bounds: the click bounds this prototype uses. BoundsOwn says it sets them itself;
	// BoundsInheritors are other items' prototypes that take their bounds from this one.
	Bounds           *int     `json:"bounds,omitempty"`
	BoundsOwn        bool     `json:"boundsOwn,omitempty"`
	BoundsInheritors []string `json:"boundsInheritors,omitempty"`
}

// Bounds is an item's click bounds as stored in the game data: an embedded struct inside a field group.
type Bounds struct {
	Blueprint uint64 `json:"blueprint"`
	Copy      uint8  `json:"copy"`
	Data      string `json:"data"` // hex
}

// RarityScript locates the end of MarvelItem.PostAdapterInit in MarvelGame.upk, where hide-by-rarity code is added,
// and the objects that code refers to (export indexes, or negative import indexes).
type RarityScript struct {
	Function    int   `json:"function"` // offset of the function export in the unpacked package
	Memory      int   `json:"memory"`   // script size in memory, where object references take 8 bytes
	Storage     int   `json:"storage"`  // script size on disk
	Rarity      int32 `json:"rarity"`
	Tooltip     int32 `json:"tooltip"`
	HideTooltip int32 `json:"hideTooltip"`
	SetHidden   int32 `json:"setHidden"`
	Mesh        int32 `json:"mesh"`
	// SetTraceBlocking switches off clicks on a hidden item's mesh.
	SetTraceBlocking int32 `json:"setTraceBlocking"`
	// LineCheck is the offset of the None tag ending Default__MarvelItem.InitialSkeletalMesh's properties, where
	// bEnableLineCheckWithBounds goes so clicks can hit an item mesh's bounding box.
	LineCheck    int `json:"lineCheck"`
	BoolProperty int `json:"boolProperty"` // name index
}

// Picking names the game-data fields that decide whether an item can be clicked.
type Picking struct {
	BoundsField     uint64 `json:"boundsField"`
	FlagField       uint64 `json:"flagField"` // ComplexPickingOnly: items have no complex collision, so none is clickable
	BoundsBlueprint uint64 `json:"boundsBlueprint"`
}

// Pin is a prototype that inherits its UnrealClass, with the class it has in the original game data.
type Pin struct {
	Path      string `json:"path"`
	Blueprint uint64 `json:"blueprint"`
	Copy      uint8  `json:"copy"`
	Field     uint64 `json:"field"`
	Asset     uint64 `json:"asset"`
}

// Slot returns the pin as the Proto that sip.Retarget writes.
func (p Pin) Slot() Proto {
	return Proto{Path: p.Path, Blueprint: p.Blueprint, Copy: p.Copy, Field: p.Field}
}

type Item struct {
	Name   string   `json:"name"`
	Icon   string   `json:"icon,omitempty"`   // texture shown for the item, such as MarvelUIIcons.Item_Unique335
	Detail string   `json:"detail,omitempty"` // what the item is, when its name alone does not say
	Hero   string   `json:"hero,omitempty"`   // the hero a unique belongs to
	Type   string   `json:"type"`
	Protos []Proto  `json:"protos"`
	Groups []string `json:"groups"`
}

// Sink is a spare item class, patched invisible, that hidden items are pointed at.
type Sink struct {
	Type  string `json:"type"`
	Asset uint64 `json:"asset"`
}

type Group struct {
	ID    string `json:"id"`
	Label string `json:"label"`
	Note  string `json:"note"`
}

type DB struct {
	Version        int              `json:"version"`
	MarvelGameSha1 string           `json:"marvelGameSha1"`
	Rarities       map[string][]int `json:"rarities"`
	Types          map[string]*Type `json:"types"`
	Items          []Item           `json:"items"`

	CalligraphySha1       string          `json:"calligraphySha1"`
	AssetPackageCacheSha1 string          `json:"assetPackageCacheSha1"`
	SoundPackageSha1      string          `json:"soundPackageSha1"`
	HUDPackageSha1        string          `json:"hudPackageSha1"` // MarvelHUD_SF.upk, which holds three mouse pointers
	Sinks                 map[string]Sink `json:"sinks"`
	Groups                []Group         `json:"groups"`
	UnrealClassFields     []uint64        `json:"unrealClassFields"`
	Picking               Picking         `json:"picking"`
	RarityScript          RarityScript    `json:"rarityScript"`
	Bounds                []Bounds        `json:"bounds"`
}

func Load() (*DB, error) {
	var d DB
	if err := json.Unmarshal(raw, &d); err != nil {
		return nil, err
	}
	return &d, nil
}

func (d *DB) Search(q string, limit int) []Item {
	q = strings.ToLower(strings.TrimSpace(q))
	var out []Item
	if q == "" {
		return out
	}
	for _, it := range d.Items {
		if strings.Contains(strings.ToLower(it.Name), q) {
			out = append(out, it)
			if len(out) == limit {
				break
			}
		}
	}
	return out
}
