// Package db holds the embedded item database generated by tools/build_db.py.
package db

import (
	_ "embed"
	"encoding/json"
	"strings"
)

//go:embed itemdb.json
var raw []byte

type Type struct {
	File       string `json:"file"`
	OrigSha1   string `json:"origSha1"`
	Category   string `json:"category"`
	RarityGlow bool   `json:"rarityGlow"`
	Glow       []int  `json:"glow"`
	Model      []int  `json:"model"`
	Name       []int  `json:"name"`
	Audio      int    `json:"audio"`    // offset of the AudioType value, 0 when the type inherits it
	AudioEnd   int    `json:"audioEnd"` // offset of the None tag ending the default object's properties
}

// Proto is one game-data prototype of an item and where its UnrealClass value is declared.
type Proto struct {
	Path      string `json:"path"`
	Blueprint uint64 `json:"blueprint"`
	Copy      uint8  `json:"copy"`
	Field     uint64 `json:"field"`
	// Inheritors are other items' prototypes that take their UnrealClass from this one.
	Inheritors []Pin `json:"inheritors,omitempty"`
}

// Pin is a prototype that inherits its UnrealClass, with the class it has in the original game data.
type Pin struct {
	Path      string `json:"path"`
	Blueprint uint64 `json:"blueprint"`
	Copy      uint8  `json:"copy"`
	Field     uint64 `json:"field"`
	Asset     uint64 `json:"asset"`
}

// Slot returns the pin as the Proto that sip.Retarget writes.
func (p Pin) Slot() Proto {
	return Proto{Path: p.Path, Blueprint: p.Blueprint, Copy: p.Copy, Field: p.Field}
}

type Item struct {
	Name   string   `json:"name"`
	Detail string   `json:"detail,omitempty"` // what the item is, when its name alone does not say
	Type   string   `json:"type"`
	Protos []Proto  `json:"protos"`
	Groups []string `json:"groups"`
}

// Sink is a spare item class, patched invisible, that hidden items are pointed at.
type Sink struct {
	Type  string `json:"type"`
	Asset uint64 `json:"asset"`
}

type Group struct {
	ID    string `json:"id"`
	Label string `json:"label"`
	Note  string `json:"note"`
}

type DB struct {
	Version        int              `json:"version"`
	MarvelGameSha1 string           `json:"marvelGameSha1"`
	Rarities       map[string][]int `json:"rarities"`
	Types          map[string]*Type `json:"types"`
	Items          []Item           `json:"items"`

	CalligraphySha1       string          `json:"calligraphySha1"`
	AssetPackageCacheSha1 string          `json:"assetPackageCacheSha1"`
	SoundPackageSha1      string          `json:"soundPackageSha1"`
	Sinks                 map[string]Sink `json:"sinks"`
	Groups                []Group         `json:"groups"`
	UnrealClassFields     []uint64        `json:"unrealClassFields"`
}

func Load() (*DB, error) {
	var d DB
	if err := json.Unmarshal(raw, &d); err != nil {
		return nil, err
	}
	return &d, nil
}

func (d *DB) Search(q string, limit int) []Item {
	q = strings.ToLower(strings.TrimSpace(q))
	var out []Item
	if q == "" {
		return out
	}
	for _, it := range d.Items {
		if strings.Contains(strings.ToLower(it.Name), q) {
			out = append(out, it)
			if len(out) == limit {
				break
			}
		}
	}
	return out
}
